"""
Standard Operating Procedure (SOP) generation.

Produces a Markdown document with full audit context.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

from affectlog.core.time import now_iso


SOP_TEMPLATE = """# Trustworthy AI Audit SOP
## Run: `{run_id}`
**Generated:** {generated_at}
**Recipe:** {recipe_name}
**Input:** `{input_path}`
**Configuration hash:** `{config_hash}`

---

## 1. Dataset Description
- **Source platform:** {source_platform}
- **Schema:** {schema}
- **Total rows processed:** {row_count:,}
- **Fields:** {fields}

## 2. Privacy Controls Applied
- **Pseudonymisation method:** {pseudo_method}
- **Fields pseudonymised:** {pseudo_fields}
- **Raw identifiers allowed:** {allow_raw}
- **Residual risk level:** {risk_level}

## 3. Transformations Applied
- CSV validated against `maskott_csv_v1` schema
- Boolean normalisation: IsViewerAuthor, IsViewerAnonymous
- Duration normalised to numeric seconds → ISO 8601
- Timestamps parsed as timezone-aware ISO 8601
- Actor EntityId pseudonymised with HMAC-SHA256
- EntityUaiCode hashed
- ActivitySessionId hashed
- xAPI normalization per ALT-AI default template

## 4. xAPI Normalization Assumptions
- Default verb: `accessed` (https://w3id.org/xapi/dod-isd/verbs/accessed)
- ViewContext mapped to verb via `configs/mappings/xapi_verbs.yaml`
- ResourceId → `object.id`
- ResourceType → `object.definition.type`
- CollectionId → `context.contextActivities.grouping`
- ActivitySessionId → `context.registration`
- Duration → `result.duration` (ISO 8601)

## 5. Metrics Summary
{metrics_section}

## 6. Key Findings
{findings_section}

## 7. Limitations
- Long-tail activity distribution: a small number of users and resources dominate event volume.
- Sparsity limits collaboration filtering performance for tail users and resources.
- No demographic attributes available — fairness assessed via activity strata only.
- Residual re-identification risk for small institutional cohorts (EntityUaiCode).
- Model not assessed in this run (dataset-only mode).

## 8. Recommended Mitigations
- Apply stratified monitoring per institution (EntityUaiCode hash).
- Use exposure/coverage-aware recommendation objectives.
- Implement k-anonymity check before any aggregate sharing.
- Schedule temporal drift review after each semester boundary.

## 9. Reproducibility
```bash
affectlog convert-csv \\
  --input {input_path} \\
  --recipe configs/recipes/{recipe_name}.yaml \\
  --output data/processed/output.jsonl \\
  --chunk-size 100000

affectlog audit \\
  --input data/processed/output.jsonl \\
  --recipe configs/recipes/{recipe_name}.yaml \\
  --output runs/{run_id}
```

## 10. Artifact List
{artifact_list}

---
*Generated by AffectLog ALT-AI v0.1.0*
"""


def build_sop(
    run_id: str,
    recipe_name: str,
    input_path: str,
    config_hash: str,
    schema_fields: list[str],
    row_count: int,
    privacy_report: Optional[dict[str, Any]] = None,
    metrics: Optional[dict[str, Any]] = None,
    stages: Optional[list[dict[str, Any]]] = None,
    artifacts: Optional[dict[str, str]] = None,
    source_platform: str = "Maskott/Tactileo",
    schema: str = "maskott_csv_v1",
) -> str:
    metrics_lines = []
    if metrics:
        for k, v in metrics.items():
            if isinstance(v, (int, float, str, bool)):
                metrics_lines.append(f"- **{k}:** {v}")
    metrics_section = "\n".join(metrics_lines) if metrics_lines else "_No metrics computed._"

    findings_lines = []
    if metrics:
        actor_gini = metrics.get("actor_gini", 0)
        resource_gini = metrics.get("resource_gini", 0)
        sparsity = metrics.get("sparsity_ratio", 0)
        if actor_gini and actor_gini > 0.6:
            findings_lines.append(f"- **High actor concentration** (Gini={actor_gini:.3f}): top users dominate activity log.")
        if resource_gini and resource_gini > 0.6:
            findings_lines.append(f"- **High resource concentration** (Gini={resource_gini:.3f}): a few resources account for most accesses.")
        if sparsity and sparsity > 0.95:
            findings_lines.append(f"- **Very sparse entity-resource matrix** (sparsity={sparsity:.3f}): typical for real-world recommendation logs.")
    findings_section = "\n".join(findings_lines) if findings_lines else "_Audit complete — no critical findings._"

    artifact_lines = []
    if artifacts:
        for name, path in artifacts.items():
            artifact_lines.append(f"- `{name}`: `{path}`")
    artifact_list = "\n".join(artifact_lines) if artifact_lines else "_None_"

    pseudo = privacy_report or {}
    risk = pseudo.get("risk_summary", {})

    return SOP_TEMPLATE.format(
        run_id=run_id,
        generated_at=now_iso(),
        recipe_name=recipe_name,
        input_path=input_path,
        config_hash=config_hash,
        source_platform=source_platform,
        schema=schema,
        row_count=row_count,
        fields=", ".join(schema_fields),
        pseudo_method="HMAC-SHA256",
        pseudo_fields=", ".join(pseudo.get("fields_pseudonymised", [])),
        allow_raw=str(pseudo.get("allow_raw_identifiers", False)),
        risk_level=risk.get("level", "unknown"),
        metrics_section=metrics_section,
        findings_section=findings_section,
        artifact_list=artifact_list,
    )


def export_sop(sop_text: str, output_path: Path | str) -> None:
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sop_text, encoding="utf-8")
